### PR TITLE
feat!: add and connect missing context, remove RemovePinWithMode

### PR DESCRIPTION
**Pull request by MichaelMure**
Arguably, `RemovePinWithMode` could be removed as it seems to be unused.

### CODE REVIEW

**Comment by MichaelMure** [comment]
Following discussion with @Jorropo, I  made PinWithMode() return an error and in turn share most of the code with Pin()

Now that PinWithMode() takes a context and return an error, there is not that much difference with Pin(). Those differences are:
- Pin() store the root node and fetch the graph if recursive
- Pin() accept an ipld.Node, PinWithMode() accept a CID (kinda meaningless)
- Pin() accept a "recurse" boolean, PinWithMode() accept a Mode, but only Direct and Recursive values

There is a case to be made to merge those or eliminate one.

**Comment by MichaelMure** [comment]
As I merged Pin() and PinWithMode(), I noticed a difference in handling. [This section](https://github.com/ipfs/go-ipfs-pinner/blob/369f7cb292574535df7d009ab4400579883da7c7/dspinner/pin.go#L234-L244) was in Pin(), but absent in PinWithMode(). I have to say, I don't really understand what that does, and don't get what the comment wants to say. Maybe @gammazero could enlightens us?

**Comment by MichaelMure** [comment]
Another difference I missed (and changed): when trying to directly pin when a recursive pin already existed, Pin() would return an error while PinWithMode() would proceed and create a duplicated pin.

I think the new behavior make sense: always return an error in that case.

**Comment by MichaelMure** [comment]
Corresponding PR in kubo: https://github.com/ipfs/kubo/pull/9557

**Review by hacdias — APPROVED** [review]
Thanks for this! The code looks good. Once https://github.com/ipfs/kubo/pull/9557 passes, I'll merge and release this.

**Pull request merged**
