### PR TITLE
wire a context in most of the ipfs data pipeline

### PR DESCRIPTION
**Pull request by gammazero**
Master issue: ipfs/go-ipfs#6803

This only does the wiring. Actual usage for cancellation, logging, or tracing is
left for future work.

This PR replaces #3

### CODE REVIEW

**Comment by BigLep** [comment]
@gammazero: thanks for handling.  Just so I have context, did you pick this up because you saw the problem when looking somewhere else, or is this connected with other work you're doing?

I do want to complete https://github.com/ipfs/go-ipfs/issues/6803 and want to make sure have the context of anything else depending on it or involved.

**Comment by gammazero** [comment]
@BigLep I did this because the code has changed enough where the [old PR](https://github.com/ipfs/go-ipfs-pinner/pull/3) this replaces was based on code that no longer exists.  So, I thought since I was the one who changed all the code, I should update or replace that PR so that it is ready to go if/when decide to move forward with https://github.com/ipfs/go-ipfs/issues/6803

**Comment by BigLep** [comment]
Rock on - thanks for seeing it and tackling it.

**Comment by gammazero** [comment]
Handled by #18

**Pull request closed without merging**
